---
sudo: false
addons:
  coverity_scan:
    project:
      description: Build submitted via Travis CI
      name: maxmind/geoip-api-java
    notification_email: dev-ci@maxmind.com
    build_command_prepend: mvn clean
    build_command: mvn -DskipTests=true compile
    branch_pattern: .*coverity.*
language: java
matrix:
  include:
    - jdk: openjdk7
    - jdk: openjdk8
    - jdk: oraclejdk8
      env: RUN_SNYK=true
env:
  global:
    - secure: d72scMGybGfXPuGKwvFXOF+3fq9d/FV5CDN1uAD5GW1r+vV0dZkKnoG3ZZ7bwikOIei4Z5zQ1oVhnPhHOS2ReCxmui1uwcGJnwl1Pwpmq/zei2sNsqyPMGA3q0v87g8wr5G+l3cRPDMBlqtjjuYHfbvyXPbYf0qTJ9NDWybg40s=
    - secure: a31E7Z7LbCoy4zVi/kQx44QoiyMwf1sQPYnGfjizZbiyUpVdBnkRo92dkcbHm44hApQPGGq8ZFXiIFlOKLyRAHAun6d+0bzanMMLPpXSXYomFVQENTXVvP+Obz9gvtevAAyN9T2YTL6r+omd4WPPKyDGOQpC+vcKbOIOc6rnq2U=
before_install:
  - "if [[ $RUN_SNYK && $SNYK_TOKEN ]]; then sudo apt-get install -y nodejs; fi"
  - "if [[ $RUN_SNYK && $SNYK_TOKEN ]]; then npm install -g snyk; fi"
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - "if [[ $RUN_SNYK && $SNYK_TOKEN ]]; then snyk test --org=maxmind; fi"
after_success:
  - "if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' && $RUN_SNYK && $SNYK_TOKEN ]]; then snyk monitor --org=maxmind --project-name=maxmind/geoip-api-java; fi"
notifications:
  email:
    on_failure: always
    on_success: change
    recipients:
      - dev-ci@maxmind.com
  slack:
    rooms:
      secure: "e4/3Esjo65Quf7MN2mXKLY0CJ23iBFPdTGdGdhE8RVPzfR2/c+YzISSOGbDFGkuQyq2kDuK94PZ3JC7xT2Cy86DEIfCc3ws46qcknrRwbCZSXLH0gTYC748JKgdaGvXxjzwCyEIoAv67EiUPPFIm+R6d01P2h4JvGpAXSvD13DM=\n"
